In [2]:
import numpy as np
import pandas as pd 
import plotly.express as px

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [5]:
df = pd.read_csv("tshirt-sizing.csv")

In [6]:
df.head()

Height (in cms)  Weight (in kgs) T Shirt Size
0              158               58            S
1              158               59            S
2              158               63            S
3              160               59            S
4              160               60            S

In [8]:
x = df.iloc[: , 0:2].values
y = df.iloc [:,2].values

In [9]:
y

array(['S', 'S', 'S', 'S', 'S', 'S', 'S', 'L', 'L', 'L', 'L', 'L', 'L',
       'L', 'L', 'L', 'L', 'L'], dtype=object)

In [10]:
x

array([[158,  58],
       [158,  59],
       [158,  63],
       [160,  59],
       [160,  60],
       [163,  60],
       [163,  61],
       [160,  64],
       [163,  64],
       [165,  61],
       [165,  62],
       [165,  65],
       [168,  62],
       [168,  63],
       [168,  66],
       [170,  63],
       [170,  64],
       [170,  68]])

In [ ]:
# encoding 

In [15]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

y = encode.fit_transform(y)

y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# split the data 

In [16]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size =.20)

In [17]:
model = KNeighborsClassifier (n_neighbors=5)

model.fit(x_train ,y_train)

KNeighborsClassifier()

In [18]:
y_pred = model.predict(x_test)

y_pred

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 1, 0, 0])

In [19]:
y_test

array([0, 1, 0, 1])

-----------------------------

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
accuracy_score(y_test,y_pred )

0.5

------------------------

In [23]:
test_errors = []

for k in range (1,10):
    model = KNeighborsClassifier (n_neighbors=k)
    model.fit(x_train, y_train)
    
    
    
    y_pred_test = model.predict(x_test)
    error = 1-accuracy_score (y_test,y_pred_test)
    test_errors.append(error)


test_errors

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

[0.25, 0.25, 0.5, 0.5, 0.5, 0.5, 0.5, 0.25, 0.5]